app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import *
from courses.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path("home/", HomeView.as_view(), name='home_view'),
    path("register/", RegisterView.as_view(), name='register_view'), 
    path('send_verification_email/', SendVerificationEmailView.as_view(), name='send_verification_email_view'),
    path('verify_email/', VerifyEmailView.as_view(), name='verify_email_view'),
    path("check_zipcode/", check_zipcode_view, name='check_zipcode'),
    path("login/", LoginView.as_view(), name='login_view'), 
    path('password_reset/<uidb64>/<token>/', MyPasswordResetConfirm.as_view(), name='password_reset_confirm'), 
    path('password_reset/done/', MyPasswordResetComplete.as_view(), name='password_reset_complete'),  
    path("change_password/", MyPasswordReset.as_view(), name='password_reset_view'),
    path("change_password/done/", MyPasswordResetDone.as_view(), name='password_reset_done'),
    path("logout/", LogoutView.as_view(), name='logout_view'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile_detail_view'),
    path('profile/<int:pk>/update', ProfileUpdateView.as_view(), name='profile_update_view'),
    path('my_courses/', MyCoursesListView.as_view(), name='my_courses_list_view'),
    path('my_courses/<int:pk>/', UserCourseDetailView.as_view(), name='my_course_detail_view'),
    path('my_courses/<int:pk>/delete/', UserCourseDeleteView.as_view(), name='my_course_delete_view'),
    path('add_course/<int:course_id>/', AddCourseView.as_view(), name='add_course_view'),
    path('courses/', CoursesListView.as_view(), name='courses_list_view'),
    path('course/<int:pk>/', CourseDetailView.as_view(), name='course_detail_view'),
    path('vacancies/', VacanciesListView.as_view(), name='vacancies_list_view'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from courses.models import Course
from django.contrib.auth.models import AbstractUser
from multipleselectionfield import MultipleSelectionField
from cpf_field.models import CPFField

    
class CustomUser(AbstractUser):

    choices_education = (
        ('Fundamental Completo', 'Fundamental Completo'),
        ('Fundamental em Andamento', 'Fundamental em Andamento'),
        ('Fundamental Incompleto', 'Fundamental Incompleto'),
        ('Médio Completo', 'Médio Completo'),
        ('Médio em Andamento', 'Médio em Andamento'),
        ('Médio Incompleto', 'Médio Incompleto'),
        ('Superior Completo', 'Superior Completo'),
        ('Superior em Andamento', 'Superior em Andamento'),
        ('Superior Incompleto', 'Superior Incompleto')
    )

    choices_areas = (
        ('Administração', 'Administração'),
        ('Contabilidade', 'Contabilidade'),
        ('Direito', 'Direito'),
        ('Economia', 'Economia'),
        ('Estética', 'Estetica'),
        ('Finanças', 'Finanças'),
        ('Gastronomia', 'Gastronomia'),
        ('Humanidades', 'Humanidades'),
        ('Linguagens', 'Linguagens'),
        ('Massoterapia', 'Massoterapia'),
        ('Saúde', 'Saúde'),
        ('Tecnologia da Informação', 'Tecnologia da Informação')
    )

    full_name = models.CharField(max_length=50, null=False, blank=False, verbose_name='Nome Completo')
    cpf = CPFField('CPF')
    date_of_birth = models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')
    email = models.EmailField(max_length=100, blank=False, null=False)
    email_verified = models.BooleanField(null=True, blank=True, default=False, verbose_name='Email Verificado')
    telephone = models.CharField(max_length=16, blank=False, null=False, verbose_name='Telefone')
    zip_code = models.CharField(max_length=9, blank=False, null=False, verbose_name='CEP')
    address = models.CharField(max_length=50, blank=False, null=False, verbose_name='Endereço')
    neighborhood = models.CharField(max_length=50, blank=False, null=False, verbose_name='Bairro')
    city = models.CharField(max_length=50, null=False, blank=False, verbose_name='Cidade')
    state = models.CharField(max_length=2, null=False, blank=False, verbose_name='Estado')
    education = models.CharField(max_length=30, choices=choices_education, verbose_name='Escolaridade')
    areas_of_interest = MultipleSelectionField(blank=True, null=True, choices=choices_areas, max_length=1000, verbose_name='Áreas de Interesse')
    photo = models.ImageField(upload_to='profile/', blank=True, null=True)
    user_courses = models.ManyToManyField(Course, related_name='courses')

    def __str__(self):
        return self.username


class UserEmailVerificationCode(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    code = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'{self.code}' 

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from .models import CustomUser
from django import forms
from django.core.exceptions import ValidationError
from datetime import date


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ("full_name", "username", "cpf", "date_of_birth", "email", 
                  "telephone", "zip_code", "address", "neighborhood",
                  "city", "state", "education", "areas_of_interest")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.date_of_birth = self.cleaned_data["date_of_birth"]

        if commit:
            user.save()
        return user
    
    def clean_areas_of_interest(self):
        areas_of_interest = self.cleaned_data.get("areas_of_interest")

        if not self.instance.is_superuser and not areas_of_interest:
            raise ValidationError("Escolha pelo menos uma Área de Interesse.")
        return areas_of_interest
    
    def clean_date_of_birth(self):
        current_date = date.today()
        date_of_birth = self.cleaned_data.get("date_of_birth")

        if date_of_birth:
            if date_of_birth > current_date:
                raise ValidationError("Informe uma data válida")            
        else: 
            raise ValidationError("Informe uma data válida")
        return date_of_birth
    
    def clean_email(self):
        email_address = self.cleaned_data['email']

        if CustomUser.objects.filter(email=email_address).exists():
            raise ValidationError(f'O email {email_address} já está vinculado a um usuário existente.')
        return email_address


class CustomUserAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        label='Usuário/Email', 
    )


class CustomReadOnlyPasswordHashWidget(forms.TextInput):

    def __init__(self, attrs=None):
        super().__init__(attrs={'readonly': 'readonly', **(attrs or {})})

    def render(self, name, value, attrs=None, renderer=None):
        if value is None:
            value = "Senha ocultada para segurança."
        return super().render(name, value, attrs, renderer)


class CustomUserChangeForm(UserChangeForm):
    password = forms.CharField(label="Senha", widget=CustomReadOnlyPasswordHashWidget)
        
    class Meta:
        model = CustomUser
        fields = ("photo", "username", "email", 
                  "telephone", "zip_code", "address", 
                  "neighborhood","city", 
                  "state", "education", "areas_of_interest")

    def clean_areas_of_interest(self):
        areas_of_interest = self.cleaned_data.get("areas_of_interest")
        if not self.instance.is_superuser and not areas_of_interest:
            raise ValidationError("Escolha pelo menos uma Área de Interesse.")
        
        return areas_of_interest
    
    def has_changed(self):
        return bool(self.changed_data)

    def save(self, commit=True):
        if self.has_changed():
            return super().save(commit)
        else:
            return self.instance


class CustomUserVerificationForm(forms.Form):
    code = forms.CharField(max_length=64)

accounts/views.py
from django.shortcuts import render, redirect
from django.shortcuts import redirect, get_object_or_404
from django.http import Http404
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import View, CreateView, UpdateView, DetailView, ListView, DeleteView, FormView
from django.contrib.auth import login, logout
from .forms import CustomUserCreationForm, CustomUserAuthenticationForm, CustomUserVerificationForm, CustomUserChangeForm
from .models import CustomUser, UserEmailVerificationCode
from utils.email_code_generator import email_code_generator
from courses.models import Course, CourseCategory
from django.http import JsonResponse
import requests
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class RegisterView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('login_view')

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Cadastro realizado com sucesso!')

        return super().form_valid(form)


class LoginView(View):

    def get(self, request):
        form = CustomUserAuthenticationForm
        return render(request, 'accounts/login.html', {'form': form})

    def post(self, request):
        form = CustomUserAuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect(reverse_lazy('courses_list_view'))
        return render(request, 'accounts/login.html', {'form': form})


class LogoutView(View):

    def get(self, request):
        logout(request)
        return redirect('home_view')


@method_decorator(login_required(login_url='login_view'), name='dispatch')
class VerifyEmailView(FormView):
    template_name = 'accounts/verify_email.html'
    form_class = CustomUserVerificationForm
    
    def get_success_url(self):
        user = self.request.user

        return reverse_lazy('profile_detail_view', kwargs={'pk': user.pk})
        

    def form_valid(self, form):
        code_entered = form.cleaned_data.get('code')

        try:
            user_code = UserEmailVerificationCode.objects.get(code=code_entered)
            self.request.user.email_verified = True
            self.request.user.save()
            user_code.delete()
            messages.success(self.request, 'Email verificado com sucesso!')

            return super().form_valid(form)
        except UserEmailVerificationCode.DoesNotExist:
            messages.error(self.request, 'Código de verificação inválido.')

            return self.form_invalid(form)


class SendVerificationEmailView(View):

    def get(self, request, *args, **kwargs):
        user = self.request.user

        if user.is_authenticated:
            if not user.email_verified:
                try:
                    old_code = UserEmailVerificationCode.objects.get(user=user)
                    if old_code:
                        old_code.delete()
                        email_code_generator(user.id)
                    else:
                        email_code_generator(user.id)
                except UserEmailVerificationCode.DoesNotExist as e:
                    email_code_generator(user.id)

        return redirect(reverse_lazy('verify_email_view'))


class MyPasswordResetConfirm(PasswordResetConfirmView):

    def form_valid(self, form):
        self.user.is_active = True
        self.user.save()
        return super(MyPasswordResetConfirm, self).form_valid(form)
    
    template_name = 'accounts/password_reset_confirm.html'


class MyPasswordResetComplete(PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'


class MyPasswordReset(PasswordResetView):
    template_name = 'accounts/password_reset_form.html'


class MyPasswordResetDone(PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


@method_decorator(login_required(login_url='login_view'), name='dispatch')
class ProfileView(DetailView):
    model = CustomUser
    template_name = 'accounts/profile.html'
    context_object_name = 'user'


@method_decorator(login_required(login_url='login_view'), name='dispatch')
class ProfileUpdateView(UpdateView):
    model = CustomUser
    form_class = CustomUserChangeForm
    template_name = 'accounts/update_profile.html'

    def get_success_url(self):
        return reverse_lazy('profile_detail_view', kwargs={'pk': self.object.pk})
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Dados atualizados com sucesso!')
        return response


@method_decorator(login_required(login_url='login_view'), name='dispatch')
class AddCourseView(View):

    def post(self, request, course_id):
        course = Course.objects.get(pk=course_id)
        request.user.user_courses.add(course)
        messages.info(request, f'Curso "{course.course_name}" adicionado com sucesso!')
        return redirect('my_courses_list_view')


@method_decorator(login_required(login_url='login_view'), name='dispatch')
class MyCoursesListView(ListView):
    model = CustomUser
    template_name = 'accounts/my_courses.html'
    context_object_name = 'courses'
    paginate_by = 3

    def get_queryset(self):
        user = self.request.user
        queryset = user.user_courses.all().order_by('course_category')
        search = self.request.GET.get('search')
        category = self.request.GET.get('category')
        if search:
            queryset = queryset.filter(course_name__icontains=search)
        if category:
            queryset = queryset.filter(course_category_id=category)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = CourseCategory.objects.all()  
        category_id = self.request.GET.get('category')
        if category_id:
            context['selected_category'] = CourseCategory.objects.get(id=category_id)
        else:
            context['selected_category'] = None
        return context


@method_decorator(login_required(login_url='login_view'), name='dispatch')
class UserCourseDetailView(DetailView):
    model = Course
    template_name = 'accounts/user_course_detail.html'
    context_object_name = 'course'


@method_decorator(login_required(login_url='login_view'), name='dispatch')
class UserCourseDeleteView(DeleteView):
    model = CustomUser
    template_name = 'accounts/user_course_delete.html'
    success_url = '/my_courses_list_view/'

    def get_object(self, queryset=None):
        course_pk = self.kwargs.get("pk") 
        course = get_object_or_404(Course, pk=course_pk)  
        user_courses = self.request.user.user_courses.all()  
        if course not in user_courses:
            raise Http404(f"Curso não encontrado.")
        return course

    def post(self, request, *args, **kwargs):
        user = self.request.user
        course_pk = self.kwargs.get("pk")  
        course = Course.objects.get(pk=course_pk)  
        user.user_courses.remove(course)  
        messages.error(request, f'Curso "{course.course_name}" excluído com sucesso!')
        return redirect('my_courses_list_view')


def check_zipcode_view(request):
    if request.method == 'GET':
        cep = request.GET.get('cep', None)
        if cep:
            url = f'https://viacep.com.br/ws/{cep}/json/'
            response = requests.get(url)
            data = response.json()
            if 'erro' not in data:
                data = {
                    'logradouro': data.get('logradouro', ''),
                    'bairro': data.get('bairro', ''),
                    'cidade': data.get('localidade', ''),
                    'estado': data.get('uf', ''),
                }
                return JsonResponse(data)
    return JsonResponse({'error': 'CEP inválido'}, status=400)

accounts/templates/accounts/login.html
{% extends "courses/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .buttons-container {
        display: flex;
        justify-content: center;
        margin-top: 20px;
        margin-bottom: 20px;
    }
  
    .btn {
        display: inline-block;
        background-color: #0096c7;
        background-color: #333;
        color: #fff;
        border: none;
        padding: 10px 20px;
        font-size: 16px;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s ease-in-out;
        margin: 0 10px;
    }
  
    .btn:hover {
        background-color: #108eb8;
    }

    ul.messages {
        padding: 0;
    }

    ul.messages li {
        list-style: none;
    }
</style>
<section class="bg-light py-5">
    <div class="container px-5 my-3 px-5">
        {% if messages %}
            <div class="container mt-3">
                {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        <div class="text-center mb-5">
            <a href="https://www.flaticon.com/br/icones-gratis/conecte-se" target="_blank"><img width="7%" class="icone-login" src="{% static 'img/login.png' %}"></a>
            <h2 class="fw-bolder my-3"> Login </h2>
        </div>
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <form method="post" class="form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="mb-3 form-check d-flex justify-content-between align-items-center">
                        <div>
                            <input type="checkbox" class="form-check-input" id="showPassword">
                            <label class="form-check-label" for="showPassword">Ver Senha</label>
                        </div>
                        <div class="text-end">
                            <a href="{% url 'password_reset_view' %}">Esqueci a senha</a> 
                        </div>
                    </div>
                    <div class="buttons-container">
                        <button class="btn btn-secondary" id="submitButton" type="submit">Enviar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script>
    $(document).ready(function() {
        $('#showPassword').click(function(){
            var passwordField = $('#id_password');
            var checkbox = $(this);

            if(passwordField.attr('type') === 'password') {
                passwordField.attr('type', 'text');
                checkbox.prop('checked', true);
                checkbox.next('label').text('Ocultar Senha');
            } else {
                passwordField.attr('type', 'password');
                checkbox.prop('checked', false);
                checkbox.next('label').text('Ver Senha');
            }
        });
    });
</script>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "courses/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>{% block head %}Alterar Senha{% endblock %}</title>
        <style>
            .buttons-container {
            display: flex;
            justify-content: center;
            margin-top: 20px;
            margin-bottom: 20px;
            }
      
            .btn {
                display: inline-block;
                background-color: #0096c7;
                background-color: #333;
                color: #fff;
                border: none;
                padding: 10px 20px;
                font-size: 16px;
                border-radius: 4px;
                cursor: pointer;
                transition: background-color 0.3s ease-in-out;
                margin: 0 10px;
            }
      
            .btn:hover {
                background-color: #108eb8;
            }
        </style>
    </head>
    <body>
    <section class="bg-light py-5">
        <div class="container px-5 my-5 px-5">
            <div class="text-center mb-5">
                <a href="https://www.flaticon.com/br/icones-gratis/senha" target="_blank"><img width="7%" class="icone-login" src="{% static 'img/senha.png' %}"></a>
                <h2 class="fw-bolder my-3"> Alterar Senha </h2>
            </div>
            <div class="row gx-5 justify-content-center">
                <div class="col-lg-6" style="text-align:center">
                    <h4> Redefinição de senha completa. </h2>
                    <br>
                    <h4> Sua senha foi definida. Você pode prosseguir e se autenticar agora. </h3>
                    <br>
                    <div class="buttons-container">
                        <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'login_view'%}">Login</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% block scripts %}
    {% endblock %}
    </body>
    </html>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "courses/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .buttons-container {
        display: flex;
        justify-content: center;
        margin-top: 20px;
        margin-bottom: 20px;
    }

    .btn {
        display: inline-block;
        background-color: #0096c7;
        background-color: #333;
        color: #fff;
        border: none;
        padding: 10px 20px;
        font-size: 16px;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s ease-in-out;
        margin: 0 10px;
    }

    .btn:hover {
        background-color: #108eb8;
    }
</style>
<section class="bg-light py-5">
    <div class="container px-5 my-5 px-5">
        <div class="text-center mb-5">
            <a href="https://www.flaticon.com/br/icones-gratis/senha" target="_blank"><img width="7%" class="icone-login" src="{% static 'img/senha.png' %}"></a>
            <h2 class="fw-bolder my-3"> Alterar Senha </h2>
        </div>
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <form method="post" class="form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="d-grid">
                        <div class="mb-3 form-check">
                            <input type="checkbox" class="form-check-input" id="showPasswords">
                            <label class="form-check-label" for="showPasswords">Ver Senha</label>
                        </div>
                        <div class="buttons-container">
                            <button class="btn btn-secondary" id="submitButton" type="submit">Enviar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
    $(document).ready(function() {
        $('#showPasswords').change(function(){
            var isChecked = $(this).is(':checked');

            if (isChecked) {
                $('#id_new_password1, #id_new_password2').attr('type', 'text');
            } else {
                $('#id_new_password1, #id_new_password2').attr('type', 'password');
            }
        });
    });
</script>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "courses/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <title>{% block title %}Registre-se{% endblock %}</title>
    </head>
    <style>
        .buttons-container {
            display: flex;
            justify-content: center;
            margin-top: 20px;
            margin-bottom: 20px;
        }
      
        .btn {
            display: inline-block;
            background-color: #0096c7;
            background-color: #333;
            color: #fff;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s ease-in-out;
            margin: 0 10px;
        }
      
        .btn:hover {
            background-color: #108eb8;
        }
    </style>
    <body>
        <section class="bg-light py-5">
            <div class="container px-5 my-3 px-5">
                <div class="text-center mb-5">
                    <a href="https://www.flaticon.com/br/icones-gratis/cadastro" target="_blank">
                        <img width="7%" class="icone-cadastro" src="{% static 'img/cadastro.png' %}">
                    </a>
                    <h2 class="fw-bolder my-3"> Cadastre-se </h2>
                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <form method="post" class="form" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <div class="mb-3 form-check">
                                <input type="checkbox" class="form-check-input" id="showPasswords">
                                <label class="form-check-label" for="showPasswords">Ver Senha</label>
                            </div>
                            <div class="buttons-container">
                                <button class="btn btn-secondary" id="submitButton" type="submit"> Enviar </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        {% block scripts %}
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/jquery.mask.min.js' %}"></script>
        <script>
            $(document).ready(function(){
                $("#id_cpf").mask("000.000.000-00");
                $("#id_date_of_birth").mask("00/00/0000");
                $("#id_telephone").mask("(00) 0 0000-0000");
                $("#id_zip_code").mask("00000-000");

                $('#id_zip_code').on('blur', function(){
                    var cep = $(this).val().replace('-', '');
                    if (cep.length === 8) {
                        $.ajax({
                            url: '/check_zipcode/',
                            data: {'cep': cep},
                            dataType: 'json',
                            success: function(data){
                                $('#id_address').val(data.logradouro);
                                $('#id_neighborhood').val(data.bairro);
                                $('#id_city').val(data.cidade);
                                $('#id_state').val(data.estado);
                            }
                        });
                    }
                });

                $('#showPasswords').change(function(){
                    var isChecked = $(this).is(':checked');
                    if (isChecked) {
                        $('#id_password1, #id_password2').attr('type', 'text');
                    } else {
                        $('#id_password1, #id_password2').attr('type', 'password');
                    }
                });
            });
        </script>
        {% endblock %}
    </body>
</html>
{% endblock %}

accounts/templates/accounts/update_profile.html
{% extends "courses/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <title>{% block title %}Editar Perfil{% endblock %}</title>
    </head>
    <style>
        .buttons-container {
            display: flex;
            justify-content: center;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        .btn {
            display: inline-block;
            background-color: #0096c7;
            background-color: #333;
            color: #fff;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s ease-in-out;
            margin: 0 10px;
          }
      
        .btn:hover {
            background-color: #108eb8;
        }
    </style>
    <body>
        <section class="bg-light py-5">
            <div class="container px-5 my-5 px-5">
                <div class="text-center mb-5">
                    </div>
                    <div class="text-center mb-5">
                    <a href="https://www.flaticon.com/br/icones-gratis/editar" target="_blank"><img width="7%" class="icone-cadastro" src="{% static 'img/editar-perfil.png' %}"></a>
                    <h2 class="fw-bolder my-3"> Editar Perfil </h2>
                    </div>
                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <form method="post" class="form" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <div class="buttons-container">
                                <input type="submit" value="Salvar Alterações" class="btn btn-primary my-4">
                                <a href="{% url 'profile_detail_view' pk=user.pk %}" class="btn btn-primary my-4">Cancelar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        {% block scripts %}
            <script src="{% static 'js/jquery.mask.min.js'%}"></script>
            <script> 
                $(document).ready(function(){
                  $("#id_telephone").mask("(00) 0 0000-0000");
                  $("#id_zip_code").mask("00000-000");
              });

                $(document).ready(function(){
                  $('#id_zip_code').on('blur', function(){
                      var cep = $(this).val().replace('-', '');
                      if (cep.length === 8) {
                          $.ajax({
                              url: '/check_zipcode/',
                              data: {'cep': cep},
                              dataType: 'json',
                              success: function(data){
                                  $('#id_address').val(data.logradouro);
                                  $('#id_neighborhood').val(data.bairro);
                                  $('#id_city').val(data.cidade);
                                  $('#id_state').val(data.estado);
                              }
                          });
                      }
                  });
              });
            </script>
        {% endblock %}
    </body>
</html>
{% endblock %}